apiVersion: apps/v1
kind: Deployment
metadata:
  name: account
  namespace: sm-banking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account # Replica set manage the pods with this selector AND immutable
  template:
    metadata:
      labels:
        app: account #all 3 pods label
    spec:
      containers:
        - name: account
          image: account:1.0.0
          imagePullPolicy: Never
          ports:
            - containerPort: 3001
          livenessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: 3001
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: bank-config
                  key: ACCOUNT_PORT
            - name: APP_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: bank-secrets
                  key: APP_DATABASE_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: bank-secrets
                  key: JWT_SECRET
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
