services:
  account:
    build: ./accounts
    image: account:1.0.0
    container_name: account
    environment:
      PORT: 3001 #inject this env var in account container
    ports:
      - "${ACCOUNT_HOST_PORT}:3001"
  customer:
    build: ./customer
    image: customer:1.0.0
    container_name: customer
    environment:
      PORT: 3000
    ports:
      - "${CUSTOMER_HOST_PORT}:3000"
  bank:
    build: ./bank
    image: bank:1.0.0
    container_name: bank
    environment:
      PORT: 4000
      ACCOUNT_API_HOST: account
      CUSTOMER_API_HOST: customer
    ports:
      - "${BANK_HOST_PORT}:4000"
    depends_on:
      - account
      - customer
  account-db:
    image: postgres:15
    container_name: account-db
    environment:
      POSTGRES_USER: account_user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: account_db
    ports:
      - "5432:5432" # optional, only if you want host access
    volumes:
      - account-db-data:/var/lib/postgresql/data

  customer-db:
    image: postgres:15
    container_name: customer-db
    environment:
      POSTGRES_USER: customer_user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: customer_db
    ports:
      - "5433:5432"
    volumes:
      - customer-db-data:/var/lib/postgresql/data
volumes:
  account-db-data:
  customer-db-data:
