services:
  account:
    build: ./accounts
    image: account:1.0.0
    container_name: account
    environment:
      PORT: 3001 #inject this env var in account container
    ports:
      - "${ACCOUNT_HOST_PORT}:3001"
  profile:
    build: ./profile
    image: profile:1.0.0
    container_name: profile
    environment:
      PORT: 3000
    ports:
      - "${PROFILE_HOST_PORT}:3000"
  bank:
    build: ./bank
    image: bank:1.0.0
    container_name: bank
    environment:
      PORT: 4000
      ACCOUNT_API_HOST: account
      PROFILE_API_HOST: profile
    ports:
      - "${BANK_HOST_PORT}:4000"
    depends_on:
      - account
      - profile
