apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-pod
  namespace: sm-banking
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth # Replica set manage the pods with this selector AND immutable
  template:
    metadata:
      labels:
        app: auth #all 3 pods label
    spec:
      containers:
        - name: auth
          image: auth:1.0.0
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: bank-config
                  key: AUTH_PORT
            - name: APP_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: bank-secrets
                  key: APP_DATABASE_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: bank-secrets
                  key: JWT_SECRET
            - name: JWT_EXPIRES_IN
              value: "1h"
            - name: NODE_ENV
              value: "production"
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
