apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-pod
  namespace: sm-banking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bank
  template:
    metadata:
      labels:
        app: bank
    spec:
      containers:
        - name: bank
          image: bank:1.0.0
          imagePullPolicy: Never
          ports:
            - containerPort: 4000
          livenessProbe:
            httpGet:
              port: 4000
              path: /health
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: 4000
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: bank-config
                  key: BANK_PORT
            - name: ACCOUNT_API_HOST
              valueFrom:
                configMapKeyRef:
                  name: bank-config
                  key: ACCOUNT_API_HOST
            - name: PROFILE_API_HOST
              valueFrom:
                configMapKeyRef:
                  name: bank-config
                  key: PROFILE_API_HOST
            - name: APP_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: bank-secrets
                  key: APP_DATABASE_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: bank-secrets
                  key: JWT_SECRET
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
