apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth # Replica set manage the pods with this selector AND immutable
  template:
    metadata:
      labels:
        app: auth #all 3 pods label
    spec:
      containers:
        - name: auth
          image: auth:2.0.0
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: "5000"
            - name: APP_DATABASE_URL
              value: "postgresql://appuser:apppass@app-db-service:5432/app_db"
            - name: JWT_SECRET
              value: "abasiccatdangerouslyelopedinthemorning"
            - name: JWT_EXPIRES_IN
              value: "1h"
            - name: NODE_ENV
              value: "production"
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
