apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bank
  template:
    metadata:
      labels:
        app: bank
    spec:
      containers:
        - name: bank
          image: bank:1.0.0
          imagePullPolicy: Never
          ports:
            - containerPort: 4000
          env:
            - name: PORT
              value: "4000"
            - name: ACCOUNT_API_HOST
              value: account-service
            - name: PROFILE_API_HOST
              value: profile-service
            - name: APP_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: bank-secrets
                  key: APP_DATABASE_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: bank-secrets
                  key: JWT_SECRET
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
