apiVersion: v1
kind: ConfigMap
metadata:
  name: bank-config
  namespace: sm-banking
data:
  APP_ENV: production
  ACCOUNT_PORT: "3001"
  AUTH_PORT: "5000"
  BANK_PORT: "4000"
  PROFILE_PORT: "3000"
  ACCOUNT_API_HOST: "account-service"
  PROFILE_API_HOST: "profile-service"
  AUTH_API_HOST: "auth-service"
  BANK_API_HOST: "bank-service"
