apiVersion: v1
kind: Secret
metadata:
  name: app-db-secret
  namespace: sm-banking
type: Opaque
stringData:
  POSTGRES_DB: appdb
  POSTGRES_USER: appuser
  POSTGRES_PASSWORD: apppass

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: app-db
  namespace: sm-banking
spec:
  serviceName: app-db-service
  replicas: 1
  selector:
    matchLabels:
      app: app-db
  template:
    metadata:
      labels:
        app: app-db
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: app-db-secret
          volumeMounts:
            - name: app-db-storage
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
  volumeClaimTemplates:
    - metadata:
        name: app-db-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: app-db-service
  namespace: sm-banking
spec:
  type: ClusterIP
  selector:
    app: app-db
  ports:
    - port: 5432
      targetPort: 5432
