apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bank-ingress
  namespace: sm-banking
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - pathType: Exact
            path: "/bank"
            backend:
              service:
                name: bank-service
                port:
                  number: 4000
          - pathType: Prefix
            path: "/auth"
            backend:
              service:
                name: auth-service
                port:
                  number: 5000
