loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    type: filesystem
  schemaConfig:
    configs:
      - from: "2024-01-01"
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: index_
          period: 24h

deploymentMode: SingleBinary

singleBinary:
  replicas: 1

# Disable everything we don't need on minikube
backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0
chunksCache:
  enabled: false
resultsCache:
  enabled: false
bloomGateway:
  replicas: 0
bloomPlanner:
  replicas: 0
