apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sm-banking-services
  namespace: observability
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - sm-banking
  selector:
    matchLabels:
      monitored: "true"
  endpoints:
    - targetPort: 4000
      path: /metrics
      interval: 15s
    - targetPort: 3001
      path: /metrics
      interval: 15s
    - targetPort: 3000
      path: /metrics
      interval: 15s
    - targetPort: 5000
      path: /metrics
      interval: 15s
