apiVersion: v1
kind: Secret
metadata:
  name: bank-secrets
type: Opaque
stringData:
  APP_DATABASE_URL: postgresql://appuser:apppass@app-db-service:5432/app_db
  JWT_SECRET: abasiccatdangerouslyelopedinthemorning
