apiVersion: v1
kind: Pod
metadata:
  name: profile-pod
  labels:
    app: profile
spec:
  containers:
    - name: profile
      image: profile:1.0.0
      imagePullPolicy: Never
      env:
        - name: PORT
          value: "3000"
      ports:
        - containerPort: 3000
      resources:
        requests:
          memory: "128Mi"
          cpu: "250m"
        limits:
          memory: "256Mi"
          cpu: "500m"
