apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: profile
  template:
    metadata:
      labels:
        app: profile
    spec:
      containers:
        - name: profile
          image: profile:1.0.0
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: APP_DATABASE_URL
              value: "postgresql://appuser:apppass@app-db--service:5432/appdb"
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
